grpc:
  server:
    port: ${APPLICATION_PORT}

spring:
  application:
    name: core
  main:
    banner-mode: off
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: ${DATASOURCE_URL}
#    username: ${DATASOURCE_USERNAME}
#    password: ${DATASOURCE_PASSWORD}
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: create # TODO switch to validate
#    show-sql: false # TODO switch switch to false
#  flyway:
#    enabled: true # TODO switch to true
#    url: ${DATASOURCE_URL}
#    user: ${DATASOURCE_USERNAME}
#    password: ${DATASOURCE_PASSWORD}
#    schemas: public
#    locations:
#      - classpath:db/postgres/migration